name: Test Docker image build and Docker-Compose run

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '30 5 * * 2,4'

jobs:
  test-docker:
    name: Build and run Docker image
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Checkout the commit triggering this job
        uses: actions/checkout@v2

      - name: Build and bring up the stack described in docker-compose.yml
        run: docker-compose up -d

      - name: Setup Node with npm cache
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies from package.json
        run: npm install

      - name: Run tests against live Postgres and Node server
        run: npm --test_live_pg_server=true --test_live_node_server=true run test:fastify

      - name: Bring down stack
        run: docker-compose down
